version: "3.8"

services:

  configserver:
    image: dawidkaszuba/config-server:latest
    ports: 
      - "8071:8071"
    networks:
      - homebudget-network
    environment:  
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8070/eureka/


  registry-service:  
    image: dawidkaszuba/registry-service:latest
    ports:
      - "8070:8070"
    networks: 
      - homebudget-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: deafult
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/    

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home_budget
    ports:
     - "3307:3306"  

  budgetservice:  
    image: dawidkaszuba/budgetservice:latest
    ports:
      - "9001:9001"
    networks: 
      - homebudget-network  
    depends_on:
      - configserver
      - registry-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 300s
    environment:
      SPRING_PROFILES_ACTIVE: deafult
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8070/eureka/


  reportservice:  
    image: dawidkaszuba/reportservice:latest
    ports:
      - "9002:9002"
    networks: 
      - homebudget-network  
    depends_on:
      - configserver
      - registry-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 300s
    environment:
      SPRING_PROFILES_ACTIVE: deafult
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8070/eureka/  
  

  gatewayserver:  
    image: dawidkaszuba/gatewayserver:latest
    ports:
      - "8072:8072"
    networks: 
      - homebudget-network  
    depends_on:
      - configserver
      - registry-service
      - budgetservice
      - reportservice
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 300s
    environment:
      SPRING_PROFILES_ACTIVE: deafult
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8070/eureka/

networks:
  homebudget-network:      
