version: "3.8"

services:

  config-server:
    image: dawidkaszuba/config-server:latest
    ports: 
      - "8071:8071"
    networks:
      - dawidkaszuba-network

  registry-service:  
    image: dawidkaszuba/registry-service:latest
    ports:
      - "8070:8070"
    networks: 
      - dawidkaszuba-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
          

  user-service:  
    image: dawidkaszuba/user-service:latest
    ports:
      - "9002:9002"
    networks: 
      - dawidkaszuba-network
    depends_on:
      - config-server
      - registry-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/ 
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://registry-service:8070/eureka    

  

  expense-service:  
    image: dawidkaszuba/expense-service:latest
    ports:
      - "9001:9001"
    networks: 
      - dawidkaszuba-network  
    depends_on:
      - config-server
      - registry-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/  
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://registry-service:8070/eureka       

networks:
  dawidkaszuba-network:      
